export const mockJobs = [
  {
    id: 1,
    title: "Frontend Developer",
    company: "PixelCraft Studios",
    location: "Remote",
    skillsRequired: ["React", "JavaScript", "CSS", "HTML", "Tailwind"],
    experienceRequired: 1,
    description:
      "Build and maintain beautiful UIs for web applications using React and Tailwind CSS.",
  },
  {
    id: 2,
    title: "Backend Developer",
    company: "CodeForge Ltd.",
    location: "Bangalore",
    skillsRequired: ["Node.js", "Express", "MongoDB", "REST APIs"],
    experienceRequired: 2,
    description:
      "Develop scalable backend services and RESTful APIs for our core products.",
  },
  {
    id: 3,
    title: "Full Stack Developer",
    company: "DevNinja",
    location: "Remote",
    skillsRequired: ["React", "Node.js", "MongoDB", "Tailwind", "JavaScript"],
    experienceRequired: 3,
    description:
      "Work on both frontend and backend of high-performing web apps using the MERN stack.",
  },
  {
    id: 4,
    title: "Machine Learning Engineer",
    company: "AI Wizardry",
    location: "Delhi",
    skillsRequired: ["Python", "TensorFlow", "scikit-learn", "Pandas", "Numpy"],
    experienceRequired: 2,
    description:
      "Design and deploy machine learning models for intelligent automation.",
  },
  {
    id: 5,
    title: "Data Scientist",
    company: "Insight Data Inc.",
    location: "Remote",
    skillsRequired: ["Python", "SQL", "PowerBI", "Pandas", "Numpy"],
    experienceRequired: 2,
    description:
      "Analyze and interpret complex datasets to drive data-informed decisions.",
  },
  {
    id: 6,
    title: "Mobile App Developer",
    company: "Appify",
    location: "Mumbai",
    skillsRequired: ["React Native", "JavaScript", "iOS", "Android"],
    experienceRequired: 1,
    description:
      "Create smooth cross-platform mobile experiences using React Native.",
  },
  {
    id: 7,
    title: "DevOps Engineer",
    company: "CloudSync",
    location: "Remote",
    skillsRequired: ["Docker", "Kubernetes", "AWS", "CI/CD", "Linux"],
    experienceRequired: 2,
    description:
      "Implement cloud infrastructure and automate deployment workflows.",
  },
  {
    id: 8,
    title: "Frontend Engineer",
    company: "UXParadise",
    location: "Remote",
    skillsRequired: ["Vue.js", "JavaScript", "SCSS", "HTML"],
    experienceRequired: 1,
    description:
      "Create elegant and responsive user experiences using Vue.js and modern CSS.",
  },
  {
    id: 9,
    title: "Software Engineer",
    company: "Codeverse",
    location: "Hyderabad",
    skillsRequired: ["C++", "DSA", "Java", "Problem Solving"],
    experienceRequired: 3,
    description: "Work on core algorithms and system-level programming.",
  },
  {
    id: 10,
    title: "AI Research Intern",
    company: "ThinkBot AI",
    location: "Remote",
    skillsRequired: ["Python", "NLP", "OpenAI", "HuggingFace", "Deep Learning"],
    experienceRequired: 0,
    description: "Research and build prototypes using cutting-edge NLP models.",
  },
  {
    id: 11,
    title: "Product Designer",
    company: "DesignHub",
    location: "Remote",
    skillsRequired: [
      "Figma",
      "UX",
      "Wireframing",
      "Prototyping",
      "Design Thinking",
    ],
    experienceRequired: 2,
    description:
      "Design intuitive and engaging user interfaces for digital products.",
  },
  {
    id: 12,
    title: "Junior Frontend Developer",
    company: "ByteLeap",
    location: "Pune",
    skillsRequired: ["HTML", "CSS", "JavaScript", "Bootstrap"],
    experienceRequired: 0,
    description: "Assist in building interactive and responsive websites.",
  },
  {
    id: 13,
    title: "React Developer",
    company: "WebSprint",
    location: "Remote",
    skillsRequired: [
      "React",
      "Redux",
      "JavaScript",
      "Tailwind",
      "API Integration",
    ],
    experienceRequired: 2,
    description: "Build modern web applications using React and Redux.",
  },
  {
    id: 14,
    title: "Cloud Engineer",
    company: "SkyNet Solutions",
    location: "Chennai",
    skillsRequired: ["AWS", "Azure", "Terraform", "Docker"],
    experienceRequired: 3,
    description: "Deploy and manage scalable infrastructure on the cloud.",
  },
  {
    id: 15,
    title: "Python Backend Developer",
    company: "DevHive",
    location: "Remote",
    skillsRequired: ["Python", "Flask", "FastAPI", "PostgreSQL"],
    experienceRequired: 2,
    description: "Develop APIs and backend services in Python using FastAPI.",
  },

  {
    id: 2,
    title: "Backend Developer",
    company: "CodeForge Ltd.",
    location: "Bangalore",
    skillsRequired: ["java", "springboot", "hibernate", "bootstap"],
    experienceRequired: 2,
    description:
      "Develop scalable backend services and RESTful APIs for our core products.",
  },
];
